version: '2'

services:
  api:
    build: .
    image: u3ix/annomania
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
      - redis
      - swagger-ui
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./test/data/mongo_import:/testdata
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.0.5
    environment:
      - API_URL=http://localhost:3000/api-docs/swagger.yaml
    ports:
      - "8080:8080"
